version: "3.9"
volumes:
  db:
    driver: local
services:
  # postgresdb:
  #   image: postgres:16-alpine
  #   restart: always
  #   container_name: ppob-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ZfcnO9WYdcbNqvRtwH4WrA99nSax2t8yBdASIoNzKCNeIs8hXI8xy7lQWrD4DeyP
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppob-app
    ports:
      - "2424:2424"
    restart: always
    volumes:
      - ./:/rest-api
    depends_on:
      - postgresdb
